<?Php
//   This class is generated by Class Automation System
//	Class Name             :   clsRegistrationManager
//	Type                   :   Manager Class
//	Description            :   This class implements the methods for DML operations of table Registration
//	Author                 :   Nishant Kumar
//	Date                   :   07-10-2021
//	Modified By            :   Nishant Kumar	
//	Date of Modification   :   08-10-2021
//	Purpose of Modification:   Adding Delete Functionality

include_once("clsRegistration.php");
include_once("clsRegistrationSet.php");

class clsRegistrationManager
{
	function SaveRegistration($objRegistration, $myConn = null)
	{

		$firstName = $objRegistration->getFirstName();
		$lastName = $objRegistration->getlastName();
		$email = $objRegistration->getEmail();
		$phone = $objRegistration->getPhone();
		$city = $objRegistration->getCity();
		$message = $objRegistration->getMessage();


		if ($firstName == null)
			$firstName = 'null';

		if ($lastName == null)
			$lastName = 'null';

		if ($email == null)
			$email = 'null';

		if ($phone == null)
			$phone = 'null';

		if ($city == null)
			$city = 'null';

		if ($message == null)
			$message = 'null';

		echo $sQuery = "insert into records(firstName, lastName, email, phone, city, message) values ('$firstName','$lastName','$email','$phone','$city', '$message')";
		if (is_resource($myConn) and get_resource_type($myConn) == 'pgsql link') {
			$rsltRegistration = pg_exec($myConn, $sQuery) or die("Couldn't execute query in clsRegistrationManager:SaveUserCategory");
			$lNumTuples = pg_cmdtuples($rsltRegistration);
		} else {
			@pg_close();
			//global $DOCUMENT_ROOT;
			include("../dbconnect.php");
			$rsltRegistration = pg_exec($connection, $sQuery) or die("Couldn't execute query in clsRegistrationManager:SaveUserCategory");
			$lNumTuples = pg_cmdtuples($rsltRegistration);
			pg_close();
		}
		return $lNumTuples;
	}

	// 	function SaveUserCategorySet($objRegistrationSet, $myConn = null)
	// 	{
	// 		$objRegistration = new clsRegistration();
	// 		$lNumRecord = $objRegistrationSet->GetCount();
	// 		$lTotalTuples = 0;
	// 		if (is_resource($myConn) and get_resource_type($myConn) == 'pgsql link') {
	// 			for ($lCount = 0; $lCount < $lNumRecord; $lCount++) {
	// 				$objRegistration = new clsRegistration();
	// 				$objRegistration = $objRegistrationSet->GetItem($lCount);

	// 				$lCompanyID = $objRegistration->getCompanyID();
	// 				$bIsActive = $objRegistration->getIsActive();
	// 				$sUserCatName = $objRegistration->getUserCatName();
	// 				$sUserCatShtName = $objRegistration->getUserCatShtName();
	// 				$lUserID = $objRegistration->getUserID();

	// 				if ($lCompanyID == null)
	// 					$lCompanyID = 'null';

	// 				if ($bIsActive == null)
	// 					$bIsActive = 'null';
	// 				else
	// 					$bIsActive = "'$bIsActive'";

	// 				if ($lUserCatID == null)
	// 					$lUserCatID = 'null';

	// 				if ($sUserCatName == null)
	// 					$sUserCatName = 'null';
	// 				else
	// 					$sUserCatName = "'$sUserCatName'";

	// 				if ($sUserCatShtName == null)
	// 					$sUserCatShtName = 'null';
	// 				else
	// 					$sUserCatShtName = "'$sUserCatShtName'";

	// 				if ($lUserID == null)
	// 					$lUserID = 'null';
	// 				$sQuery = "insert into usercategory(companyid,isactive,usercatname,usercatshtname,userid) values ($lCompanyID,$bIsActive,$sUserCatName,$sUserCatShtName,$lUserID)";
	// 				$rsltUserCategory = pg_exec($myConn, $sQuery) or die("Couldn't execute query in clsRegistrationManager:SaveUserCategorySet");
	// 				$lNumTuples = pg_cmdtuples($rsltUserCategory);
	// 				if ($lNumTuples != 0) {
	// 					$lTotalTuples = $lTotalTuples + 1;
	// 				}
	// 			}
	// 		} else {
	// 			//global $DOCUMENT_ROOT;
	// 			include("../dbconnect.php");
	// 			pg_exec($connection, 'begin');
	// 			for ($lCount = 0; $lCount < $lNumRecord; $lCount++) {
	// 				$objRegistration = new clsRegistration();
	// 				$objRegistration = $objRegistrationSet->GetItem($lCount);

	// 				$lCompanyID = $objRegistration->getCompanyID();
	// 				$bIsActive = $objRegistration->getIsActive();
	// 				$sUserCatName = $objRegistration->getUserCatName();
	// 				$sUserCatShtName = $objRegistration->getUserCatShtName();
	// 				$lUserID = $objRegistration->getUserID();

	// 				if ($lCompanyID == null)
	// 					$lCompanyID = 'null';

	// 				if ($bIsActive == null)
	// 					$bIsActive = 'null';
	// 				else
	// 					$bIsActive = "'$bIsActive'";

	// 				if ($lUserCatID == null)
	// 					$lUserCatID = 'null';

	// 				if ($sUserCatName == null)
	// 					$sUserCatName = 'null';
	// 				else
	// 					$sUserCatName = "'$sUserCatName'";

	// 				if ($sUserCatShtName == null)
	// 					$sUserCatShtName = 'null';
	// 				else
	// 					$sUserCatShtName = "'$sUserCatShtName'";

	// 				if ($lUserID == null)
	// 					$lUserID = 'null';
	// 				$sQuery = "insert into usercategory(companyid,isactive,usercatname,usercatshtname,userid) values ($lCompanyID,$bIsActive,$sUserCatName,$sUserCatShtName,$lUserID)";
	// 				$rsltUserCategory = pg_exec($connection, $sQuery) or die("Couldn't execute query in clsRegistrationManager:SaveUserCategorySet");
	// 				$lNumTuples = pg_cmdtuples($rsltUserCategory);
	// 				if ($lNumTuples != 0) {
	// 					$lTotalTuples = $lTotalTuples + 1;
	// 				}
	// 			}
	// 			pg_exec($connection, 'commit');
	// 			pg_close();
	// 		}
	// 		return $lTotalTuples;
	// 	}

	function RetrieveRegistrationSet($sQuery)
	{
		//global $DOCUMENT_ROOT;

		include("../dbconnect.php");
		// echo $sQuery;
		$objRegistration = new clsRegistration();
		$objRegistrationSet = new clsRegistrationSet();
		$rsltRegistration = pg_exec($connection, $sQuery) or die("Couldn't execute query in clsRegistrationManager:RetrieveRegistration.");
		$lNumRows = pg_numrows($rsltRegistration);
		if ($lNumRows == 0) {
			pg_close();
			return $objRegistrationSet;
		}
		for ($lCount = 0; $lCount < $lNumRows; $lCount++) {
			$objRegistration = new clsRegistration();
			$arrRegistration = pg_fetch_array($rsltRegistration, $lCount);
			// $objRegistration->setCompanyID($arrUserCategory[companyid]);
			$objRegistration->setId($arrRegistration['id']);
			$objRegistration->setFirstName($arrRegistration['firstname']);
			$objRegistration->setlastName($arrRegistration['lastname']);
			$objRegistration->setEmail($arrRegistration['email']);
			$objRegistration->setPhone($arrRegistration['phone']);
			$objRegistration->setCity($arrRegistration['city']);
			$objRegistration->setMessage($arrRegistration['message']);
			$objRegistrationSet->Add($objRegistration);
		}
		pg_close();
		return $objRegistrationSet;
	}

	// function RetrieveRegistrationSet($sQuery)
	// {
	// 	//global $DOCUMENT_ROOT;

	// 	include("../dbconnect.php");

	// 	echo $sQuery;

	// 	$objRegistration = new clsRegistration();
	// 	$rsltRegistration = pg_exec($connection, $sQuery) or die("Couldn't execute query in clsRegistrationManager:RetrieveUserCategory.");
	// 	$lNumRows = pg_numrows($rsltRegistration);
	// 	if ($lNumRows == 0) {
	// 		pg_close();
	// 		return null;
	// 	}
	// $arrRegistration = pg_fetch_array($rsltRegistration, 0);
	// $objRegistration->setId($arrRegistration['id']);
	// $objRegistration->setFirstName($arrRegistration['firstname']);
	// $objRegistration->setlastName($arrRegistration['lastname']);
	// $objRegistration->setEmail($arrRegistration['email']);
	// $objRegistration->setPhone($arrRegistration['phone']);
	// $objRegistration->setCity($arrRegistration['city']);
	// $objRegistration->setMessage($arrRegistration['message']);

	// 	$objRegistrationSet->Add($objRegistration);

	// 	pg_close();
	// 	return $objRegistration;
	// }

	function UpdateRegistration($objRegistration, $myConn = null)
	{
		//global $DOCUMENT_ROOT;


		$id = $objRegistration->getId();
		$firstName = $objRegistration->getFirstName();
		$lastName = $objRegistration->getlastName();
		$email = $objRegistration->getEmail();
		$phone = $objRegistration->getPhone();
		$city = $objRegistration->getCity();
		$message = $objRegistration->getMessage();


		if ($id == null)
			$id = 'null';

		if ($firstName == null)
			$firstName = 'null';

		if ($lastName == null)
			$lastName = 'null';

		if ($email == null)
			$email = 'null';

		if ($phone == null)
			$phone = 'null';

		if ($city == null)
			$city = 'null';

		if ($message == null)
			$message = 'null';

		$sQuery = "update records set
			firstName='$firstName',
			lastName='$lastName',
			email='$email',
			phone='$phone',
			city='$city',
			message='$message'
			where id=$id";
		if (is_resource($myConn) and get_resource_type($myConn) == 'pgsql link') {
			$rsltRegistration = pg_exec($myConn, $sQuery) or die("Couldn't execute query in clsRegistrationManager:UpdateRegistration");
			$lNumTuples = pg_cmdtuples($rsltRegistration);
		} else {
			@pg_close();
			//global $DOCUMENT_ROOT;
			include("../dbconnect.php");
			$rsltRegistration = pg_exec($connection, $sQuery) or die("Couldn't execute query in clsRegistrationManager:UpdateRegistration");
			$lNumTuples = pg_cmdtuples($rsltRegistration);
			pg_close();
		}
		return $lNumTuples;
	}
	// 	function UpdateUserCategorySet($objRegistrationSet, $myConn = null)
	// 	{
	// 		$objRegistration = new clsRegistration();
	// 		$lNumRecord = $objRegistrationSet->GetCount();
	// 		$lTotalTuples = 0;
	// 		if (is_resource($myConn) and get_resource_type($myConn) == 'pgsql link') {
	// 			for ($lCount = 0; $lCount < $lNumRecord; $lCount++) {
	// 				$objRegistration = new clsRegistration();
	// 				$objRegistration = $objRegistrationSet->GetItem($lCount);

	// 				$lCompanyID = $objRegistration->getCompanyID();
	// 				$bIsActive = $objRegistration->getIsActive();
	// 				$lUserCatID = $objRegistration->getUserCatID();
	// 				$sUserCatName = $objRegistration->getUserCatName();
	// 				$sUserCatShtName = $objRegistration->getUserCatShtName();
	// 				$lUserID = $objRegistration->getUserID();

	// 				if ($lCompanyID == null)
	// 					$lCompanyID = 'null';

	// 				if ($bIsActive == null)
	// 					$bIsActive = 'null';
	// 				else
	// 					$bIsActive = "'$bIsActive'";

	// 				if ($lUserCatID == null)
	// 					$lUserCatID = 'null';

	// 				if ($sUserCatName == null)
	// 					$sUserCatName = 'null';
	// 				else
	// 					$sUserCatName = "'$sUserCatName'";

	// 				if ($sUserCatShtName == null)
	// 					$sUserCatShtName = 'null';
	// 				else
	// 					$sUserCatShtName = "'$sUserCatShtName'";

	// 				if ($lUserID == null)
	// 					$lUserID = 'null';

	// 				$sQuery = "update usercategory set
	// 				companyid=$lCompanyID,
	// 				isactive=$bIsActive,
	// 				usercatname=$sUserCatName,
	// 				usercatshtname=$sUserCatShtName,
	// 				userid=$lUserID
	// 				where usercatid=$lUserCatID";
	// 				$rsltUserCategory = pg_exec($myConn, $sQuery) or die("Couldn't execute query in clsRegistrationManager:UpdateUserCategorySet");
	// 				$lNumTuples = pg_cmdtuples($rsltUserCategory);
	// 				if ($lNumTuples != 0) {
	// 					$lTotalTuples = $lTotalTuples + 1;
	// 				}
	// 			}
	// 		} else {
	// 			//global $DOCUMENT_ROOT;
	// 			include("../dbconnect.php");
	// 			pg_exec($connection, 'begin');
	// 			for ($lCount = 0; $lCount < $lNumRecord; $lCount++) {
	// 				$objRegistration = new clsRegistration();
	// 				$objRegistration = $objRegistrationSet->GetItem($lCount);

	// 				$lCompanyID = $objRegistration->getCompanyID();
	// 				$bIsActive = $objRegistration->getIsActive();
	// 				$lUserCatID = $objRegistration->getUserCatID();
	// 				$sUserCatName = $objRegistration->getUserCatName();
	// 				$sUserCatShtName = $objRegistration->getUserCatShtName();
	// 				$lUserID = $objRegistration->getUserID();

	// 				if ($lCompanyID == null)
	// 					$lCompanyID = 'null';

	// 				if ($bIsActive == null)
	// 					$bIsActive = 'null';
	// 				else
	// 					$bIsActive = "'$bIsActive'";

	// 				if ($lUserCatID == null)
	// 					$lUserCatID = 'null';

	// 				if ($sUserCatName == null)
	// 					$sUserCatName = 'null';
	// 				else
	// 					$sUserCatName = "'$sUserCatName'";

	// 				if ($sUserCatShtName == null)
	// 					$sUserCatShtName = 'null';
	// 				else
	// 					$sUserCatShtName = "'$sUserCatShtName'";

	// 				if ($lUserID == null)
	// 					$lUserID = 'null';
	// 				$sQuery = "update usercategory set
	// 				companyid=$lCompanyID,
	// 				isactive=$bIsActive,
	// 				usercatname=$sUserCatName,
	// 				usercatshtname=$sUserCatShtName,
	// 				userid=$lUserID
	// 				where usercatid=$lUserCatID";
	// 				$rsltUserCategory = pg_exec($connection, $sQuery) or die("Couldn't execute query in clsRegistrationManager:UpdateUserCategorySet");
	// 				$lNumTuples = pg_cmdtuples($rsltUserCategory);
	// 				if ($lNumTuples != 0) {
	// 					$lTotalTuples = $lTotalTuples + 1;
	// 				}
	// 			}
	// 			pg_exec($connection, 'commit');
	// 			pg_close();
	// 		}
	// 		return $lTotalTuples;
	// 	}

	function DeleteRegistration($obj, $myConn = null)
	{
		//global $DOCUMENT_ROOT;


		$id = $obj->getId();

		if ($id == null)
			$id = 'null';
		$sQuery = "delete from records
			where id=$id";
		if (is_resource($myConn) and get_resource_type($myConn) == 'pgsql link') {
			$rsltRegistration = pg_exec($myConn, $sQuery) or die("Couldn't execute query in clsRegistrationManager:DeleteRegistration");
			$lNumTuples = pg_cmdtuples($rsltRegistration);
		} else {
			@pg_close();
			//global $DOCUMENT_ROOT;
			include("../dbconnect.php");
			$rsltRegistration = pg_exec($connection, $sQuery) or die("Couldn't execute query in clsRegistrationManager:DeleteRegistration");
			$lNumTuples = pg_cmdtuples($rsltRegistration);
			pg_close();
		}
		return $lNumTuples;
	}
	// 
}
