<?Php
//   This class is generated by Class Automation System
//	Class Name             :   clsRegistrationSet
//	Type                   :   Collection Class
//	Description            :   This class manages the collection of objects of class clsRegistration
//	Author                 :   Nishant Kumar
//	Date                   :   07-10-2021
//	Modified By            :   
//	Date of Modification   :   
//	Purpose of Modification:   

include_once("clsRegistration.php");

class clsRegistrationSet
{
	var $aRegistration = array();
	function Add($obj)
	{
		$this->aRegistration[] = $obj;
	}
	function GetCount()
	{
		return count($this->aRegistration);
	}
	function GetItem($lIndex)
	{
		$lLastEntry = $this->GetCount();
		if ($lIndex < 0 || $lIndex > $lLastEntry - 1) {
			echo " MyError: Illegal index Passed to  clsRegistrationSet:GetItem()";
			exit;
		}
		return $this->aRegistration[$lIndex];
	}
	function Remove($lIndex)
	{
		$lLastEntry = $this->GetCount();
		if ($lIndex < 0 || $lIndex > $lLastEntry - 1) {
			echo " MyError: Illegal index Passed to  clsRegistrationSet:Remove()";
			exit;
		}
		for ($i = $lIndex; $i < $lLastEntry; $i++) {
			$this->aRegistration[$i] = $this->aRegistration[$i + 1];
		}
		array_pop($this->aRegistration);
	}
}
